### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by ixiting** [klshv/transport#1]
Некорректно работает функция удаления и добавления остановочного комплекса.
При удалении программа закрывается. 
При добавлении без изменений программа так же закрывается с ошибкой.
![image](https://user-images.githubusercontent.com/16041974/173107669-cdd285e3-90e2-497f-95ab-58966bc7dc8b.png)

**Comment by klshv** [comment]
commit 76305de4f35b13603855d538ba679b5a402b21da
